apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "default-name" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name | default "default-name" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default "default-name" }}
    spec:
      containers:
      - name: server
        image: {{ .Values.image | default "nginx:latest" }}
        ports:
        - containerPort: {{ .Values.port | default 80 }}
        env:
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        readinessProbe:
          {{- if .Values.readinessProbe }}
          {{- if .Values.readinessProbe.httpGet }}
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path | default "/" }}
            port: {{ .Values.readinessProbe.httpGet.port | default 80 }}
            {{- if .Values.readinessProbe.httpGet.httpHeaders }}
            httpHeaders:
            {{- toYaml .Values.readinessProbe.httpGet.httpHeaders | nindent 12 }}
            {{- end }}
          {{- else if .Values.readinessProbe.grpc }}
          grpc:
            port: {{ .Values.readinessProbe.grpc.port | default 50051 }}
          {{- end }}
          {{- end }}
        livenessProbe:
          {{- if .Values.livenessProbe }}
          {{- if .Values.livenessProbe.httpGet }}
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path | default "/" }}
            port: {{ .Values.livenessProbe.httpGet.port | default 80 }}
            {{- if .Values.livenessProbe.httpGet.httpHeaders }}
            httpHeaders:
            {{- toYaml .Values.livenessProbe.httpGet.httpHeaders | nindent 12 }}
            {{- end }}
          {{- else if .Values.livenessProbe.grpc }}
          grpc:
            port: {{ .Values.livenessProbe.grpc.port | default 50051 }}
          {{- end }}
          {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "100m" }}
            memory: {{ .Values.resources.requests.memory | default "64Mi" }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | default "200m" }}
            memory: {{ .Values.resources.limits.memory | default "128Mi" }}
