apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "default-service" }}
spec:
  selector:
    app: {{ .Values.name | default "default-name" }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.port | default 80 }}
  type: ClusterIP
