image:
  repository: gcr.io/google-samples/microservices-demo/recommendationservice
  tag: v0.9.0

service:
  type: ClusterIP
  port: 8080

env:
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  DISABLE_PROFILER: "1"

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi

probes:
  readiness:
    periodSeconds: 5
    grpcPort: 8080
  liveness:
    periodSeconds: 5
    grpcPort: 8080

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
