image:
  repository: gcr.io/google-samples/microservices-demo/loadgenerator
  tag: v0.9.0

env:
  FRONTEND_ADDR: frontend:80
  USERS: "10"

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

initContainers:
  - name: frontend-check
    image: busybox:latest
    command:
      - /bin/sh
      - -exc
      - |
        echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
        STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
        if test $STATUSCODE -ne 200; then
            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
            exit 1
        fi
    env:
      - name: FRONTEND_ADDR
        value: frontend:80
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
