image:
  repository: gcr.io/google-samples/microservices-demo/emailservice
  tag: v0.9.0

service:
  type: ClusterIP
  port: 5000
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    periodSeconds: 5
    grpcPort: 8080
  liveness:
    periodSeconds: 5
    grpcPort: 8080

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
