image:
  repository: gcr.io/google-samples/microservices-demo/frontend
  tag: v0.9.0

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  CURRENCY_SERVICE_ADDR: currencyservice:7000
  CART_SERVICE_ADDR: cartservice:7070
  RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
  SHIPPING_SERVICE_ADDR: shippingservice:50051
  CHECKOUT_SERVICE_ADDR: checkoutservice:5050
  AD_SERVICE_ADDR: adservice:9555
  ENABLE_PROFILER: "0"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 10
    httpGet:
      path: /_healthz
      port: 8080
      httpHeaders:
      - name: Cookie
        value: shop_session-id=x-readiness-probe
  liveness:
    initialDelaySeconds: 10
    httpGet:
      path: /_healthz
      port: 8080
      httpHeaders:
      - name: Cookie
        value: shop_session-id=x-liveness-probe

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
